CREATE TABLE BOOKS(
ID NUMBER PRIMARY KEY,
TITLE NVARCHAR2 (250),
YEAR NUMBER,
AUTHOR NVARCHAR2 (250));

CREATE TABLE REVIEWERS(
ID NUMBER PRIMARY KEY,
NAME NVARCHAR2 (250));

CREATE TABLE RATINGS(
REVIEWER_ID NUMBER,
BOOK_ID NUMBER,
RATING NUMBER,
RATING_DATE DATE);

--AÑADIMOS FK
ALTER TABLE RATINGS ADD CONSTRAINT FK_RATINGS_REVIEWER_ID
FOREIGN KEY(REVIEWER_ID)
REFERENCES REVIEWERS(ID);

ALTER TABLE RATINGS ADD CONSTRAINT FK_RATINGS_BOOK_ID
FOREIGN KEY(BOOK_ID)
REFERENCES BOOKS(ID);

--INSERTAMOS DATOS
INSERT INTO BOOKS VALUES(101, 'A TALES OF TWO CITIES', 1859,'CHARLES DICKENS');
INSERT INTO BOOKS VALUES(102, 'THE LORD OF RINGS', 1955,'J.R.R. TOLKIEN');
INSERT INTO BOOKS VALUES(103, 'THE HOBBIT', 1937,NULL);
INSERT INTO BOOKS VALUES(104, 'THE LITTLE PRINCESS', 1943,'ANTOINE SAINT-EXUPERY');

INSERT INTO REVIEWERS VALUES(15201,'JOE MARTINEZ');
INSERT INTO REVIEWERS VALUES(53202,'ALICE LEWIS');
INSERT INTO REVIEWERS VALUES(44203,'JOHN SMITH');

INSERT INTO RATINGS VALUES(15201,101,2,'11-02-2015');
INSERT INTO RATINGS VALUES(15201,101,4,'16-06-2015');
INSERT INTO RATINGS VALUES(53202,103,4,NULL);

SELECT E.NAME, B.TITLE, RS.RATING, RS.RATING_DATE
FROM BOOKS B INNER JOIN RATINGS RS
ON B.ID = RS.BOOK_ID INNER JOIN REVIEWERS E
ON E.ID=RS.REVIEWER_ID;